import type { TowerConfig, TowerId } from '../types';

export const TOWER_CONFIGS: Record<TowerId, TowerConfig> = {
  arrow: {
    id: 'arrow',
    name: '箭塔',
    shortName: '箭',
    cost: 35,
    damage: 13,
    range: 150,
    attackSpeed: 2.2,
    projectileSpeed: 420,
    attackType: 'single',
    color: 0x6fcf97,
    projectileColor: 0xe8f6d8,
    upgradeLevels: [
      { level: 2, cost: 45, damage: 15, attackSpeed: 2.6 },
      { level: 3, cost: 70, damage: 18, attackSpeed: 3.0 },
      { level: 4, cost: 110, damage: 21, attackSpeed: 3.2, special: { doubleShotChance: 0.2 } },
    ],
  },
  cannon: {
    id: 'cannon',
    name: '炮塔',
    shortName: '炮',
    cost: 75,
    damage: 40,
    range: 190,
    attackSpeed: 0.65,
    projectileSpeed: 270,
    attackType: 'aoe',
    aoeRadius: 65,
    color: 0xf2994a,
    projectileColor: 0xffca80,
    upgradeLevels: [
      { level: 2, cost: 90, damage: 52 },
      { level: 3, cost: 130, range: 220, aoeRadius: 78 },
      { level: 4, cost: 180, damage: 68, aoeRadius: 92 },
    ],
  },
  ice: {
    id: 'ice',
    name: '冰塔',
    shortName: '冰',
    cost: 60,
    damage: 8,
    range: 155,
    attackSpeed: 0.9,
    projectileSpeed: 300,
    attackType: 'single',
    effects: [{ id: 'slow', multiplier: 0.7, duration: 2 }],
    color: 0x56ccf2,
    projectileColor: 0xb9f2ff,
    upgradeLevels: [
      { level: 2, cost: 75, damage: 10, effects: [{ id: 'slow', multiplier: 0.62, duration: 2 }] },
      { level: 3, cost: 105, range: 185 },
      {
        level: 4,
        cost: 150,
        damage: 14,
        special: { freezeChance: 0.12 },
        effects: [{ id: 'slow', multiplier: 0.55, duration: 2.2 }],
      },
    ],
  },
  poison: {
    id: 'poison',
    name: '毒塔',
    shortName: '毒',
    cost: 55,
    damage: 6,
    range: 165,
    attackSpeed: 1,
    projectileSpeed: 310,
    attackType: 'single',
    effects: [{ id: 'poison', damagePerSecond: 5, duration: 5 }],
    color: 0xbb6bd9,
    projectileColor: 0xe8a4ff,
    upgradeLevels: [
      { level: 2, cost: 70, damage: 8, effects: [{ id: 'poison', damagePerSecond: 7, duration: 5 }] },
      { level: 3, cost: 100, effects: [{ id: 'poison', damagePerSecond: 8, duration: 7 }] },
      {
        level: 4,
        cost: 145,
        damage: 11,
        special: { poisonSpreadRadius: 70 },
        effects: [{ id: 'poison', damagePerSecond: 9, duration: 7 }],
      },
    ],
  },
};

export const TOWER_LIST = Object.values(TOWER_CONFIGS);
